### PR TITLE
enhancements to rich list

### PR DESCRIPTION
**Pull request by allenan**
adds some additional columns to the rich list:

image

### CODE REVIEW

**Comment by abhay** [comment]
The context is useful but wondering if adding 2 new columns when the majority of the values in those columns are `0` is the right UX?

**Comment by allenan** [comment]
> The context is useful but wondering if adding 2 new columns when the majority of the values in those columns are `0` is the right UX?

I think it's fine

**Comment by abhay** [comment]
> > The context is useful but wondering if adding 2 new columns when the majority of the values in those columns are `0` is the right UX?
> 
> I think it's fine

It's useful enough to not feel strongly about it. 🚢

**Comment by danielcolinjames** [comment]
yeah I agree it's worth considering the usefulness of adding columns, but I think it's probably fine for this case, since this page isn't really linked to anywhere else on the site and I think one of the major reasons people would go to this page is probably answered by those columns :)

**Review by danielcolinjames — APPROVED** [review]
looks great! 🔥

**Pull request merged**
