### PR TITLE
Humanize pie chart text [txnid]

### PR DESCRIPTION
**Pull request by guiferrpereira**
Found the same issue as #200 on transactions page:

Screenshot 2021-02-13 at 17 43 43

Screenshot 2021-02-13 at 17 43 17

### CODE REVIEW

**Comment by filoozom** [comment]
I guess you might as well implement the coloring scheme like #170 and #205 while you're at it 😜

**Comment by guiferrpereira** [comment]
> I guess you might as well implement the coloring scheme like #170 and #205 while you're at it 😜

sure ;)

**Comment by guiferrpereira** [comment]
@filoozom ✅

**Review by danielcolinjames — APPROVED** [review]
very nice!! 😄  🔥  great work

and thanks for adding that suggestion @filoozom  👍 

merging this!

**Pull request merged**
