### PR TITLE
Display hotspot location (h3)

### PR DESCRIPTION
**Pull request by rootulp**
Fixes https://github.com/helium/explorer/issues/326

Let me know if you have any feedback on the icon, tooltip text, or styling!

### CODE REVIEW

**Comment by cokes518** [comment]
this looks great! no changes requested from me in terms of UI or copy.

**Comment by danielcolinjames** [comment]
awesome! I think it fits slightly better up under the map: 
Screen Shot 2021-04-20 at 5 31 04 PM

so going to move it up there I think (will push up a commit shortly) and might also borrow an existing location icon from the app as well. didn't mean to intrude on your PR, just started playing with the code and figured I might as well just add on haha

but overall this looks great, nice work! thanks for doing that 😄

**Comment by rootulp** [comment]
>  didn't mean to intrude on your PR

No problemo! Thanks for taking over. I like where you moved it

**Review by danielcolinjames — APPROVED** [review]
🚀

**Pull request merged**
