### PR TITLE
Update "Synced"/"Syncing" to "Connected"

### PR DESCRIPTION
**Pull request by danielcolinjames**
addresses # 1 of #857 

Screen Shot 2022-02-23 at 3 52 01 PM

we can also change the header from "Sync Status" to something else if that would make sense. maybe "Hotspot Status", or "Connection Status"?

### CODE REVIEW

**Comment by cokes518** [comment]
following the discussion with chain gang, we'll use a chain variable to decide when to display light hotspot-related UI.

chain var: `poc_challenger_type` would be `validator`

cc @allenan

**Comment by danielcolinjames** [comment]
(meant to add this screenshot on friday)
Screen Shot 2022-03-18 at 4 27 26 PM

**Review by allenan — APPROVED** [review]
code looks good 👍

**Comment by cokes518** [comment]
noticed a potential issue where the online status is pulling from the API `status: online` which uses stale online logic. might need an API update on testnet to follow what will be available on mainnet (which is: if there is activity in the last 36 hours, the hotspot is online).

**Comment by danielcolinjames** [comment]
documenting for future: as of this PR, the way the status works is:
- if `hotspot.status.online === 'offline'`, it shows "Offline"
- otherwise:
    - if the `poc_challenger_type` chain var is set to `'validator'` it shows "Connected"
    - if the `poc_challenger_type` chain var is _not_ set to `'validator'`, it'll show "Syncing" / "Synced" depending on block height

**Pull request merged**
