### PR TITLE
feat: upgrades & SSR conversion

### PR DESCRIPTION
**Pull request by Ehesp**
- Upgrade to React 17
- Upgrade to Next 10
- SSR `hotspots/:id` pages
- SSR `accounts/richet` page
- SSR `accounts/:id` page
- SSR `/` (homepage) page

### CODE REVIEW

**Comment by abhay** [comment]
I love the progress. Is it reasonable to cherry pick the upgrade commit and merge first?

**Comment by Ehesp** [comment]
Yeah that's reasonable. There's not really anything depending on that apart from the fallback flags.

**Comment by abhay** [comment]
I wouldn't stop progress on the branch though. Can easily rebase.

**Comment by allenan** [comment]
@Ehesp getting the following error from the build log when trying to deploy a review app for this PR:

```
-----> Installing dependencies
       Installing node modules (yarn.lock)
       yarn install v1.22.10
       [1/4] Resolving packages...
       error Your lockfile needs to be updated, but yarn was run with `--frozen-lockfile`.
       info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
-----> Build failed
 !     Outdated Yarn lockfile
       Your application contains a Yarn lockfile (yarn.lock) which does not
       match the dependencies in package.json. This can happen if you use npm
       to install or update a dependency instead of Yarn.
       Please run the following command in your application directory and check
       in the new yarn.lock file:
       $ yarn install
       $ git add yarn.lock
       $ git commit -m "Updated Yarn lockfile"
       $ git push heroku main
    
       https://help.heroku.com/TXYS53YJ
 !     Push rejected, failed to compile Node.js app.
 !     Push failed
```

**Pull request merged**
