### PR TITLE
Made changes for Discord server channel names and grammatical errors

### PR DESCRIPTION
**Pull request by arijitdas123student**
Hope this PR gets merged soon! 
Thanks

### CODE REVIEW

**Comment by PharkMillups** [comment]
Looks good.

**Review by danielcolinjames — APPROVED** [review]
@arijitdas123student  nice!! looks good to me, thank you for contributing! 😄

**Comment by arijitdas123student** [comment]
Cool thanks for merging the PR @danielcolinjames ! 🙂 
Also, I wonder if you guys have some swags left for giveaway as a part of [this](https://blog.helium.com/helium-hackathon-explorer-edition-faf842800f46) ?!

**Comment by danielcolinjames** [comment]
@arijitdas123student  we definitely still have some swag left and the hackathon will still be running until the 28th of February yeah 😄  

but while we do really appreciate anyone contributing to our repos, to be eligible for swag, a PR will have to be a little bit more substantial than fixing up typos and/or grammar 🙂  I recommend regularly keeping an eye on issues that have the tag "Hackathon" on them, as we've been adding new ones every now and then: https://github.com/helium/explorer/issues?q=is%3Aopen+is%3Aissue+label%3AHackathon

and feel free to reach out to me if you want some help getting started on how you might solve a specific issue!

**Comment by danielcolinjames** [comment]
@arijitdas123student #193  might be a good one?  👀   I just added the Hackathon label to it

**Comment by arijitdas123student** [comment]
Awesome! Thanks for sharing @danielcolinjames :)

**Pull request merged**
