### PR TITLE
Add heliumCockpit

### PR DESCRIPTION
**Pull request by mbecker81**

### CODE REVIEW

**Comment by cokes518** [comment]
i can't seem to sign up for an account. do you have a dummy login i can use to check this out?

**Comment by mbecker81** [comment]
> i can't seem to sign up for an account. do you have a dummy login i can use to check this out?

Hi @cokes518, I created an dummy account for you:
demo@heliumcockpit.io / Demo2022

**Comment by mbecker81** [comment]
Hi @cokes518 
Have you had time to look at our application?

**Comment by cokes518** [comment]
Thanks for the login. I was able to use the credentials to check out the website. Note that you're making calls to the public API and will likely be throttled as your service grows. I recommend you pull those queries in house.

image

**Review by cokes518 — APPROVED** [review]

**Comment by mbecker81** [comment]
Hi @cokes518 
Thanks for the approval. We moved the calls from server- to client-side because we got a lot of "too mandy requests" errors. We will change that again but what can we do to prevent this errors? For example is it possible to whitelist our server?

**Comment by Ryan-Goldstein** [comment]
Running your own ETL (https://github.com/helium/blockchain-etl) and querying that rather than the public API is probably the way to go.

**Pull request merged**
