### PR TITLE
Refactor [hotspotid].js page to use @helium/http

### LINKED ISSUE #307: Reroute requests to helium-js
There are a few instances where explorer talks to the API directly instead of helium-js. this makes it hard for us to switch between wtf and production.

### PR DESCRIPTION
**Pull request by MohdImran001**
Fixes #307 
Hi @danielcolinjames, please review this PR.

Before merging this PR we need to upgrade the `@helium/http` package to version 3.35 in the master branch.
In the master branch, `yarn.lock` and `package.json` files is using version 3.31.

`yarn.lock` file
```
"@helium/http@^3.31.0":
  version "3.31.0"
  resolved "https://registry.yarnpkg.com/@helium/http/-/http-3.31.0.tgz#68c95326248ed0229d334dd7a45aa9df6e5821ca"
  integrity sha512-MnHf2n4Ju0qsWois0+o/nlNpXAP5UBxtPx/ezzjkKSapzHwOAFynJ9PHL3xbye1phs8LdCsoRzfMxYIOFPrEyw==
  dependencies:
    "@helium/currency" "^3.25.1"
    axios "^0.21.1"
    camelcase-keys "^6.2.2"
    qs "^6.9.3"
    retry-axios "^2.1.2"
```

### CODE REVIEW

**Comment by MohdImran001** [comment]
Hi @danielcolinjames, please give some feedback.

**Comment by danielcolinjames** [comment]
hey @MohdImran001 sorry I didn't look at this very quickly. it looks good to me and seems to work! I've just pushed a commit that updates helium-js as I'm pretty sure there aren't any breaking changes. let's let that deploy on the preview Heroku URL and then test it a bit to make sure, but then this should be good to merge :)

**Comment by MohdImran001** [comment]
Hi @danielcolinjames, I tried the deployment on this [hotspot.](https://helium-explorer-pr-372.herokuapp.com/hotspots/112aRgPxohcf5K2c8dSPekTxvR7jfWsSd1miA9rGtWymSKmgqQ5w). 
It looks good to me.

**Review by danielcolinjames — APPROVED** [review]
thanks again for doing this @MohdImran001! will merge tomorrow 🙂  thanks for your patience

**Pull request merged**
