### PR TITLE
Truncated proof and members content

### PR DESCRIPTION
**Pull request by MohdImran001**
PR for #27 

I have made some changes to TxnView Page to make the design better. I m truncating the long proof content and list members to fit them into one line that makes Transaction more readable.

### CODE REVIEW

**Comment by danielcolinjames** [comment]
Hey @MohdImran001, thanks for doing this work! It looks great. I added a few things to take it a bit further:

- made the members into a list and gave them links so you can click to each hotspot's detail page
- added a toggle button so you can turn truncation of the proof on and off

**Comment by danielcolinjames** [comment]
Screenshots of how it looks with these changes:

Screen Shot 2020-10-16 at 11 47 16 AM
Screen Shot 2020-10-16 at 11 47 30 AM


@allenan No rush but if you get a chance to review it that would be great :) (not sure how to trigger a deploy of a contributor PR)

**Comment by MohdImran001** [comment]
Hii @danielcolinjames. Thank you for your feedback. I am looking forward to work on more issues. I just have a small request. I am participating in Hacktoberfest and It would be great if you could add a `hacktoberfest-accepted` label on this PR. It would help me to claim a Limited Edition T-Shirt or get a tree planted.

**Comment by abhay** [comment]
We can do that do that for sure, @MohdImran001.

**Comment by MohdImran001** [comment]
Thanks a lot !. @abhay and @danielcolinjames

**Comment by danielcolinjames** [comment]
The forked repo here seems to have been deleted, so I can't commit to this PR to bring it up to speed with master before merging, so I've created another PR here instead with all the commits: #64

**Pull request closed without merging**
