### PR TITLE
Change pie chart legend color and humanize text

### PR DESCRIPTION
**Pull request by guiferrpereira**
@danielcolinjames believe that this handles https://github.com/helium/explorer/issues/200

### CODE REVIEW

**Comment by allenan** [comment]
nice @guiferrpereira. Do we need to add a human readable name for `price_oracle_v1`? Any other ones we're missing? looking at https://helium-explorer-pr-205.herokuapp.com/blocks/712479

**Comment by guiferrpereira** [comment]
> nice @guiferrpereira. Do we need to add a human readable name for `price_oracle_v1`? Any other ones we're missing? looking at https://helium-explorer-pr-205.herokuapp.com/blocks/712479

Screenshot 2021-02-11 at 23 39 57

Didn't notice that, I think the rest is all ok. Do you want me to fix it on this PR, or should we do another one for this?

**Review by danielcolinjames — APPROVED** [review]
yeah good call, makes sense to fix it in #190 I think :) looks good!

**Comment by danielcolinjames** [comment]
@guiferrpereira could you tell me your Discord handle here so the marketing team can get your info and we can get some swag to you? :)

**Pull request merged**
