### PR TITLE
fix state channel close map markers

### PR DESCRIPTION
**Pull request by MattCarlos96**
closes https://github.com/helium/explorer/issues/50

### CODE REVIEW

**Review by DGKSK8LIFE — APPROVED** [review]

**Review by danielcolinjames — CHANGES_REQUESTED** [review]
nice! didn't realize it would be such a simple fix 😄 

looking at the map, I notice that the zoom/centering of the mapbox is hardcoded to focus on the USA, and now that there are hotspots outside the USA/North America, I think we should make the map focus and zoom depending on where the markers are

luckily we have a handy function that does that already :) it's called `findBounds`, and you can find it in `/components/Txns/utils.js`, and you can see an example of how to implement it in `/components/Txns/ConsensusMapbox.js`

would be awesome if you could add that to this and then we'll get it merged!

thanks for contributing!! 🔥

**Comment by MattCarlos96** [comment]
I can do that! :D

**Comment by danielcolinjames** [comment]
awesome! 😄

**Review by danielcolinjames — APPROVED** [review]
awesome, looks good! 🔥

**Pull request merged**
