### PR TITLE
add network rewards back

### PR DESCRIPTION
**Pull request by allenan**

### CODE REVIEW

**Review by danielcolinjames — APPROVED** [review]
sorry! I think I intended to approve this but forgot

**Comment by cokes518** [comment]
let's get this to build to a temp deploy and check that it's not going to break the API if we merge.

**Comment by cokes518** [comment]
needs to be reworked.

**Comment by jwmakesgames** [comment]
Resolution To Be integrated in Following Updates  From 2.02 to 6+

**Review by jwmakesgames — APPROVED** [review]

**Review by jwmakesgames — APPROVED** [review]

**Comment by madninja** [comment]
@jwmakesgames one and only warning to please stop spamming GitHub repos with useless approvals and messages

**Pull request closed without merging**
