### PR TITLE
Improve error pages

### PR DESCRIPTION
**Pull request by Astrochamp**
Added custom 404 and 500 error pages, to replace default next.js templates. 
New pages have several helpful links, as well as a navbar on top of the page

Completed together with @SourishS17

Note from @SourishS17:
If you want, you can change the links that we have on the error pages to whatever you would like, but we just set them to some [helium.com](https://helium.com) links

### CODE REVIEW

**Comment by danielcolinjames** [comment]
nice! @Astrochamp  sorry I didn't get to reviewing this today, but I'll give it a review tomorrow and don't worry, we'll still count this as a valid submission for the hackathon, and since it's a 2x you'll each get something :)

if you could reply here with your discord handles I'll get you in touch with Tim who will help with that

**Comment by Astrochamp** [comment]
My discord is Astrochamp#8718 and @SourishS17's discord is !Sourish17#3977

**Comment by Astrochamp** [comment]
Fixed 500 error page not working, it now redirects to a 500 page when this error is encountered

**Comment by Astrochamp** [comment]
Edited CSS to match edits from #246

**Comment by Astrochamp** [comment]
I've spotted some conflicts in the CSS files (mine are missing some changes). I'll resolve these later today 🙂

**Comment by Astrochamp** [comment]
Huh - any ideas why the deployment failed 🤔?

**Comment by danielcolinjames** [comment]
I think there might be a missing `}` in the CSS file :) I checked the branch out locally a couple days ago and had done the same as you did above (merge master in and fix conflicts) but didn't push it up haha

I might do a few small edits locally and push them to this branch in the next little while. hoping to merge this soon, sorry it's taken awhile!

**Comment by danielcolinjames** [comment]
this is great! really nice work @Astrochamp. I took a stab at getting the styles on the 404 page a bit more consistent with the rest of the site :)
Screen Shot 2021-03-12 at 12 21 09 AM

I'll probably do the same for the 500 page tomorrow and then hopefully get this merged in and deployed!

I also updated the styling to use [Tailwind](https://tailwindcss.com) instead of custom class names in the Explorer.css file as we're trying to transition the site to using Tailwind to keep styles consistent moving forward. my bad that the styling sort of changed out from under you between when you started working on this and when I'm reviewing it

in case you're interested in contributing more in the future, I recently did a bit of a write-up on the styling philosophy of the website overall as we go forward :) https://github.com/helium/explorer#styling

**Review by danielcolinjames — APPROVED** [review]
thanks again for getting this PR together @Astrochamp! 🔥  merging it now

**Comment by Astrochamp** [comment]
Thanks @danielcolinjames for merging! 

I've just noticed that helium.com still uses the default error pages, would we be able to customise these ones too?

**Comment by danielcolinjames** [comment]
@Astrochamp good question! right now the helium.com codebase isn't public, but we'll probably do something similar there and use this code as a reference :)

**Pull request merged**
